### PR TITLE
Add support for shadow DOM closed mode

### LINKED ISSUE #74: Add support for {mode: 'closed'}
The current implementation of `register(..., {shadow: true})`, always attaches the shadow DOM in `{mode: 'open'}`. This is a request to add some support for `{mode: 'closed'}` as well.

Relevant docs:
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM#basic_usage

Screen Shot 2022-09-09 at 3 14 20 AM

I'm happy to send a PR to support the above. The way I see it there are two options:

1) In addition to the option`{shadow: true}`, add support for `{shadow: 'open'}` and `{shadow: 'closed'}`.

2) Add a new option called `mode`, e.g.: `{shadow: true, mode: 'closed'}`.

Let me know which option is preferred and I'm happy to send over the PR, including updating the `@types/` package.

### PR DESCRIPTION
**Pull request by stevenle**
Fixes #74

### CODE REVIEW

**Review by marvinhagemeister — APPROVED** [review]
Looks good! Thanks for making a PR 👍  Is it possible to add a test case for this so that we don't regress on this in the future?

**Comment by stevenle** [comment]
I added two tests (one for `{mode: 'open'}` and one for `{mode: 'closed'}`. Would appreciate another look to make sure I'm following the correct patterns for this project.

(Note: I needed to update puppeteer in order for it to work on my Macbook with Apple Silicon. `npm install` wasn't working for me, so I used `yarn` and so the `package-lock.json` file wasn't updated.)

**Review by marvinhagemeister — APPROVED** [review]
Awesome, thanks a bunch for adding tests 👍

**Comment by stevenle** [comment]
Thanks for the review! What's the next step from here? I assume you'll handle the merge and the publish to npm?

**Comment by AGrabovajFitA** [comment]
Hi @marvinhagemeister , what's the next step here. Can we get this out?

**Comment by leifriksheim** [comment]
Hi, any updates on this PR? 
I would love for this to get merged as we wouldn't have to keep our own fork of this project. 🙏

**Review by MattCCC — APPROVED** [review]

**Comment by MattCCC** [comment]
Test CI still fails it seems

**Review by MattCCC — APPROVED** [review]

**Comment by bhollis** [comment]
@marvinhagemeister if you update this branch it may pass now.

**Comment by bhollis** [comment]
Nice, the tests are passing!

**Comment by janbiasi** [comment]
Seems like this is not included in the latest version, when can we expect this to get released?

**Comment by HowieG** [comment]
Also need this change and wondering when it will be released!

**Comment by HowieG** [comment]
@janbiasi dang I just realized the last publish to npm was in 2020 😲 . Haven't encountered this before do we just clone the repo then?

**Comment by HowieG** [comment]
@janbiasi seems we can change our package.json to grab from the repo directly

{
  "dependencies": {
    "preact-custom-element": "https://github.com/preactjs/preact-custom-element.git"
  }
}

**Comment by janbiasi** [comment]
> @janbiasi seems we can change our package.json to grab from the repo directly
> 
> { "dependencies": { "preact-custom-element": "https://github.com/preactjs/preact-custom-element.git" } }

Well yes, that works as a workaround at least 😄 But I'm really questioning why this feature wasn't released via NPM.
Maybe @marvinhagemeister can tell us more details about the official release.

**Comment by HowieG** [comment]
@janbiasi yooo we did it!! #84 hahaha

**Comment by HowieG** [comment]
@janbiasi FYI there wasn't a subsequent change to the types for this change. It's simple but need to go through DefinitelyTyped's kinda thorough PR process. I'm just ignoring for now.

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/1709f05c255d8f1c30d115fb216722c39f6a7283

**Comment by janbiasi** [comment]
@HowieG Yea! 😎 Thanks for the support on this one. I think I should have time to go through the definitely typed PR process pretty soon but as you said, it also works without them - I'll keep you updated :)

**Comment by rschristian** [comment]
Alternatively, I think we're happy to add the types here. I don't think there's any real need to use DefinitelyTyped

**Comment by janbiasi** [comment]
> Alternatively, I think we're happy to add the types here. I don't think there's any real need to use DefinitelyTyped

Thanks for the hint @rschristian, I just opened a PR https://github.com/preactjs/preact-custom-element/pull/85 for this.

cc @HowieG

**Pull request merged**
