### PR TITLE
Release 4.0.0

### LINKED ISSUE #31: publish to npm?
looks like the latest version, 3.0.0, was published in 2018.

### LINKED ISSUE #34: New release
Are there any plans to cut a new release of this package anytime soon? There are several post 3.0 improvements already merged to the main branch. If there is anything I can do to in order to help facilitate a new release, please tell.

### PR DESCRIPTION
**Pull request by marvinhagemeister**
Fixes #34, fixes #31 .

### CODE REVIEW

**Comment by marvinhagemeister** [comment]
@bspaulding I seem to lack permissions to publish on npm 🙈

**Comment by bspaulding** [comment]
@marvinhagemeister ah, dang. What's your npm handle? I'll invite you as maintainer.

**Comment by marvinhagemeister** [comment]
@bspaulding Awesome, thank you so much for helping out 🙌  It's @marvinhagemeister , same as here in GitHub 🎉

**Comment by bspaulding** [comment]
ok added. 👍

**Comment by marvinhagemeister** [comment]
mh I'm still running into the same permission error as before. Can you check that I have the "write access" ? Or maybe npm just needs a bit of to apply these changes 🙈

**Comment by marvinhagemeister** [comment]
Just tried again and now it worked :raised_hands: I guess I should be more patient with npm in the future :sweat_smile:

**Comment by developit** [comment]
Heh - sorry for being MIA on this! Npm permissions often take an hour to propagate.

**Pull request merged**
